#!/usr/bin/env bash
# This script tells a story based on the contents of the /etc/passwd file.

# Read each line of /etc/passwd
while IFS=: read -r username _ group_id _ _ home shell; do
  # Format the output as a story
  echo "The user $username is part of the $group_id gang, lives in $home and rides $shell. $group_id's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
