#!/usr/bin/env bash

# Specify the location of the Apache access log file
# Path to the apache log file
log_file="apache-access.log"

# Using awk to extract IP and HTTP status code
awk '{print $1, $9}' "$log_file"
