#!/usr/bin/env bash
# File path of the Apache access log

# Path to the Apache log file
log_file="apache-access.log"

# Extract IP and HTTP status code from the log file, count occurrences, and sort by occurrences
awk '{print $1, $9}' "$log_file" | sort | uniq -c | sort -nr | awk '{printf "%6d %s %s\n", $1, $2, $3}'
