#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

counter=1
while [ $counter -le 10 ]
do
  echo "Best School"
  ((counter++))  # Increment the counter by 1
done
