#!/usr/bin/env bash
# This script displays the time from 0 hours to 12 hours, with minutes from 1 to 59 for each hour.

hour=0
while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo $minute
    ((minute++))
  done
  ((hour++))
done
