#!/usr/bin/env bash
#!/bin/bash

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If a PID is found, send the kill signal to terminate it
if [[ -n "$pid" ]]; then
    kill "$pid"
fi
