#!/usr/bin/env bash
#!/bin/bash

# Disable SC2009 warning
# shellcheck disable=SC2009

# Find the PID of the 4-to_infinity_and_beyond process by using a unique identifier
pid=$(ps aux | grep '[4]-to_infinity_and_beyond' | awk '{print $2}')

# If the process is found, stop it
if [[ -n "$pid" ]]; then
    # Send a SIGINT signal to terminate the process
    kill -SIGINT "$pid"
fi
