#!/usr/bin/env bash
#!/bin/bash

# Define a handler for SIGTERM that displays "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

# Loop indefinitely and print "To infinity and beyond" every 2 seconds
while true; do
    echo "To infinity and beyond"
    sleep 2
done
