#!/usr/bin/env bash
#!/bin/bash

# Find the PID of the 7-highlander process by making sure to match the correct pattern
pid=$(ps aux | grep '[7]-highlander' | awk '{print $2}')

# If the PID is found, send SIGTERM to terminate the process
if [[ -n "$pid" ]]; then
    kill -SIGTERM "$pid"
fi
