#!/usr/bin/env bash
#!/bin/bash

# Find the PID of the 7-highlander process
pid=$(ps aux | grep '[7]-highlander' | awk '{print $2}')

# If the PID is found, send a SIGTERM to terminate the process
if [[ -n "$pid" ]]; then
    kill -SIGTERM "$pid"
fi
