#!/usr/bin/env bash
#!/bin/bash

# Find the PID of the 7-highlander process
pid=$(pgrep -f '[7]-highlander')

# If the PID is found, send SIGKILL to terminate the process
if [[ -n "$pid" ]]; then
    kill -9 "$pid"
 # Onlyprint "OK" once after killing thr process
    echo "OK"
fi
